apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/app:latest
          imagePullPolicy: Never
